#https://ci.apache.org/projects/flink/flink-docs-release-1.3/setup/docker.html
#https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/
version: "3.8"
#Now, to the point, if you have your containers on one network, you do not need any further 
#special specification. Unless you specify otherwise, the default network driver is bridge. 
#So, if you specify your docker-compose.yml as following, you should have all your container 
#on one network and aware of each other automatically.
# there 3 container:
# 1 x  jobmanager
# 2 x  taskmanager ( taskmanager1 and taskmanager2)
# each taskmanager have 2 slot ==> total slot = 2taskmanager x 2slot = 4 slot

networks:
  flink_network:
    driver: bridge

services:
  jobmanager:
    image: duonghuynhbaocr/apache-flink-arm64:1.13.2
    expose:
      - "6123"
    ports: #exposed to both host machines and  other  docker_compose services
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_network

  taskmanager1:
    image: duonghuynhbaocr/apache-flink-arm64:1.13.2
    expose: #Ports are not exposed to host machines, only exposed to other docker_compose services
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    networks:
      - flink_network

  taskmanager2:
    image: duonghuynhbaocr/apache-flink-arm64:1.13.2
    expose: #Ports are not exposed to host machines, only exposed to other docker_compose services
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    networks:
      - flink_network

