#https://ci.apache.org/projects/flink/flink-docs-release-1.3/setup/docker.html
version: "2.1"
services:
  jobmanager:
    image: apacheflink_apache_flinkpy:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: apacheflink_apache_flinkpy:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager